runtime: nodejs22 # Ensure you specify the correct Node.js version
instance_class: F2 # Adjust the instance class as needed

env_variables:
  NODE_ENV: production

handlers:
  - url: / # Serve the main page
    static_files: build/index.html
    upload: build/index.html

  - url: /(.*) # Serve all other static files
    static_files: build/\1
    upload: build/(.*)

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
